version: '2'
services:
  unifi-controller:
    build: .
    image: dbrosy/unifi-controller
    ports:
     - "8080:8080"
     - "8443:8443"
     - "8843:8843"
     - "3478:3478/udp"
     - "6789:6789"
    container_name: unifi
